# Site settings
title: Charlie Ward
email: charlieward18@gmail.com
description: This is a website where I predominantly blog about my exeriences as a junior webdeveloper and any issues related to tech.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://wardch.github.io" # the base hostname & protocol for your site
twitter_username: CharlieDubs23
github_username:  wardch

# Build settings
markdown: kramdown
